-- Drop old tables first to avoid errors
DROP TABLE AuditLog CASCADE CONSTRAINTS;
DROP TABLE TRANSACTIONS CASCADE CONSTRAINTS;
DROP TABLE ACCOUNTS CASCADE CONSTRAINTS;
DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;

-- Create tables
CREATE TABLE CUSTOMERS (CustomerID NUMBER PRIMARY KEY, Name VARCHAR2(100), DOB DATE, Balance NUMBER, LastModified DATE, IsVIP VARCHAR2(5) DEFAULT 'FALSE');
CREATE TABLE ACCOUNTS (AccountID NUMBER PRIMARY KEY, CustomerID NUMBER, AccountType VARCHAR2(20), Balance NUMBER, LastModified DATE, CONSTRAINT fk_customer FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID));
CREATE TABLE TRANSACTIONS (TransactionID NUMBER PRIMARY KEY, AccountID NUMBER, TransactionDate DATE, Amount NUMBER, TransactionType VARCHAR2(10), CONSTRAINT fk_account FOREIGN KEY (AccountID) REFERENCES ACCOUNTS(AccountID));
CREATE TABLE AuditLog (LogID NUMBER PRIMARY KEY, TransactionID NUMBER, LogDate DATE DEFAULT SYSDATE, Action VARCHAR2(50));

COMMIT;
/