spring.application.name=edge-service-routing
server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=example_route
spring.cloud.gateway.server.webflux.routes[0].uri=https://example.org
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/example/**

