server.port=8761
spring.application.name=eureka-server

# Standalone mode: Prevent Eureka from trying to register with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false