# Server configuration
server.port=9090
spring.application.name=api-gateway

# Eureka Registry Location
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Discovery Locator configuration
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Actuator settings to expose endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.info.enabled=true